# Generated by Django 5.0.3 on 2024-04-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarient',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='SizeVarient',
            new_name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_varient',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='product_desription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_varient',
            new_name='size_variant',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='catgories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
